version: '3'
services:
  mongo_service:
    image: mongo:latest
    # image: mongodb/mongodb-community-server:latest
    container_name: mongo_service
    restart: always
    ports:
      - 27017:27017
    env_file: .env
    volumes:
      - mongodbdata:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  bot:
    build:
      context: .
    env_file: .env
    ports:
      - 3000:3000
    depends_on:
      - mongo_service

volumes:
  mongodbdata:
    driver: local
